version: 1
formatters:
  simple:
    format: "%(levelname)s: %(message)s"
  detailed:
    format: "%(asctime)s %(process)d:%(module)s [%(levelname)s] %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: log/imus.log
    maxBytes: 104960000 #100kb
    backupCount: 10
root:
  level: DEBUG
  handlers: [console, file]
